### ISSUE TITLE
Autocomplete commands

### ISSUE THREAD

**Issue by waldyrious** [leostera/tldr.js#7]
It'd be neat if the input field could show a list of possible autocompletions based on the commands available on tldr-pages

**Comment by leostera** [comment]
As of right now, we are making 4 requests to look for the page in each of the OS's folders.

I can see this working charmingly if the tldr-pages repo had an index of pages we could get. Otherwise the application would make way too many requests.

I'll fork their repo and come up with something, an index could be easily built using

```
ls -1 pages/** | grep .md | awk -F"." '{print $1}' > pages/index.md
```

Probably can be made shorter.

**Comment by leostera** [comment]
Depends on: https://github.com/tldr-pages/tldr/pull/267.

**Comment by waldyrious** [comment]
Was this implemented? It doesn't seem to work in the demo version.

**Comment by leostera** [comment]
Hey @waldyrious I closed this as this repo is unmaintained altogether. For the cross reference issue see https://github.com/ostera/tldr.jsx/issues/8

**Comment by waldyrious** [comment]
Thanks for the clarification :+1: but shouldn't you add a deprecation / abandonment notice in the readme?
